Insert into companies(name,sector,industry) values('A. O. Smith','Industrials','Building Products');
Insert into companies(name,sector,industry) values('Abbott','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('AbbVie','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Accenture','Information Technology','IT Consulting & Other Services');
Insert into companies(name,sector,industry) values('Adobe Inc.','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Advanced Micro Devices','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('AES Corporation','Utilities','Independent Power Producers & Energy Traders');
Insert into companies(name,sector,industry) values('Aflac','Financials','Life & Health Insurance');
Insert into companies(name,sector,industry) values('Agilent Technologies','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Air Products and Chemicals','Materials','Industrial Gases');
Insert into companies(name,sector,industry) values('Airbnb','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('Akamai','Information Technology','Internet Services & Infrastructure');
Insert into companies(name,sector,industry) values('Albemarle Corporation','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('Alexandria Real Estate Equities','Real Estate','Office REITs');
Insert into companies(name,sector,industry) values('Align Technology','Health Care','Health Care Supplies');
Insert into companies(name,sector,industry) values('Allegion','Industrials','Building Products');
Insert into companies(name,sector,industry) values('Alliant Energy','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Allstate','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Alphabet Inc. (Class A)','Communication Services','Interactive Media & Services');
Insert into companies(name,sector,industry) values('Alphabet Inc. (Class C)','Communication Services','Interactive Media & Services');
Insert into companies(name,sector,industry) values('Altria','Consumer Staples','Tobacco');
Insert into companies(name,sector,industry) values('Amazon','Consumer Discretionary','Broadline Retail');
Insert into companies(name,sector,industry) values('Amcor','Materials','Paper & Plastic Packaging Products & Materials');
Insert into companies(name,sector,industry) values('Ameren','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('American Airlines Group','Industrials','Passenger Airlines');
Insert into companies(name,sector,industry) values('American Electric Power','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('American Express','Financials','Consumer Finance');
Insert into companies(name,sector,industry) values('American International Group','Financials','Multi-line Insurance');
Insert into companies(name,sector,industry) values('American Tower','Real Estate','Telecom Tower REITs');
Insert into companies(name,sector,industry) values('American Water Works','Utilities','Water Utilities');
Insert into companies(name,sector,industry) values('Ameriprise Financial','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Ametek','Industrials','Electrical Components & Equipment');
Insert into companies(name,sector,industry) values('Amgen','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Amphenol','Information Technology','Electronic Components');
Insert into companies(name,sector,industry) values('Analog Devices','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Ansys','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Aon','Financials','Insurance Brokers');
Insert into companies(name,sector,industry) values('APA Corporation','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Apple Inc.','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('Applied Materials','Information Technology','Semiconductor Materials & Equipment');
Insert into companies(name,sector,industry) values('Aptiv','Consumer Discretionary','Automotive Parts & Equipment');
Insert into companies(name,sector,industry) values('Arch Capital Group','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Archer-Daniels-Midland','Consumer Staples','Agricultural Products & Services');
Insert into companies(name,sector,industry) values('Arista Networks','Information Technology','Communications Equipment');
Insert into companies(name,sector,industry) values('Arthur J. Gallagher & Co.','Financials','Insurance Brokers');
Insert into companies(name,sector,industry) values('Assurant','Financials','Multi-line Insurance');
Insert into companies(name,sector,industry) values('AT&T','Communication Services','Integrated Telecommunication Services');
Insert into companies(name,sector,industry) values('Atmos Energy','Utilities','Gas Utilities');
Insert into companies(name,sector,industry) values('Autodesk','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Automatic Data Processing','Industrials','Human Resource & Employment Services');
Insert into companies(name,sector,industry) values('AutoZone','Consumer Discretionary','Automotive Retail');
Insert into companies(name,sector,industry) values('AvalonBay Communities','Real Estate','Multi-Family Residential REITs');
Insert into companies(name,sector,industry) values('Avery Dennison','Materials','Paper & Plastic Packaging Products & Materials');
Insert into companies(name,sector,industry) values('Axon Enterprise','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Baker Hughes','Energy','Oil & Gas Equipment & Services');
Insert into companies(name,sector,industry) values('Ball Corporation','Materials','Metal, Glass & Plastic Containers');
Insert into companies(name,sector,industry) values('Bank of America','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('Bank of New York Mellon','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Bath & Body Works, Inc.','Consumer Discretionary','Other Specialty Retail');
Insert into companies(name,sector,industry) values('Baxter International','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Becton Dickinson','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Berkshire Hathaway','Financials','Multi-Sector Holdings');
Insert into companies(name,sector,industry) values('Best Buy','Consumer Discretionary','Computer & Electronics Retail');
Insert into companies(name,sector,industry) values('Bio-Rad','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Bio-Techne','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Biogen','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('BlackRock','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Blackstone','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Boeing','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Booking Holdings','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('BorgWarner','Consumer Discretionary','Automotive Parts & Equipment');
Insert into companies(name,sector,industry) values('Boston Properties','Real Estate','Office REITs');
Insert into companies(name,sector,industry) values('Boston Scientific','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Bristol Myers Squibb','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('Broadcom Inc.','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Broadridge Financial Solutions','Industrials','Data Processing & Outsourced Services');
Insert into companies(name,sector,industry) values('Brown & Brown','Financials','Insurance Brokers');
Insert into companies(name,sector,industry) values('Brown�Forman','Consumer Staples','Distillers & Vintners');
Insert into companies(name,sector,industry) values('Builders FirstSource','Industrials','Building Products');
Insert into companies(name,sector,industry) values('Bunge Global SA','Consumer Staples','Agricultural Products & Services');
Insert into companies(name,sector,industry) values('Cadence Design Systems','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Caesars Entertainment','Consumer Discretionary','Casinos & Gaming');
Insert into companies(name,sector,industry) values('Camden Property Trust','Real Estate','Multi-Family Residential REITs');
Insert into companies(name,sector,industry) values('Campbell Soup Company','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Capital One','Financials','Consumer Finance');
Insert into companies(name,sector,industry) values('Cardinal Health','Health Care','Health Care Distributors');
Insert into companies(name,sector,industry) values('CarMax','Consumer Discretionary','Automotive Retail');
Insert into companies(name,sector,industry) values('Carnival','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('Carrier Global','Industrials','Building Products');
Insert into companies(name,sector,industry) values('Catalent','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('Caterpillar Inc.','Industrials','Construction Machinery & Heavy Transportation Equipment');
Insert into companies(name,sector,industry) values('Cboe Global Markets','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('CBRE Group','Real Estate','Real Estate Services');
Insert into companies(name,sector,industry) values('CDW','Information Technology','Technology Distributors');
Insert into companies(name,sector,industry) values('Celanese','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('Cencora','Health Care','Health Care Distributors');
Insert into companies(name,sector,industry) values('Centene Corporation','Health Care','Managed Health Care');
Insert into companies(name,sector,industry) values('CenterPoint Energy','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('CF Industries','Materials','Fertilizers & Agricultural Chemicals');
Insert into companies(name,sector,industry) values('CH Robinson','Industrials','Air Freight & Logistics');
Insert into companies(name,sector,industry) values('Charles River Laboratories','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Charles Schwab Corporation','Financials','Investment Banking & Brokerage');
Insert into companies(name,sector,industry) values('Charter Communications','Communication Services','Cable & Satellite');
Insert into companies(name,sector,industry) values('Chevron Corporation','Energy','Integrated Oil & Gas');
Insert into companies(name,sector,industry) values('Chipotle Mexican Grill','Consumer Discretionary','Restaurants');
Insert into companies(name,sector,industry) values('Chubb Limited','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Church & Dwight','Consumer Staples','Household Products');
Insert into companies(name,sector,industry) values('Cigna','Health Care','Health Care Services');
Insert into companies(name,sector,industry) values('Cincinnati Financial','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Cintas','Industrials','Diversified Support Services');
Insert into companies(name,sector,industry) values('Cisco','Information Technology','Communications Equipment');
Insert into companies(name,sector,industry) values('Citigroup','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('Citizens Financial Group','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Clorox','Consumer Staples','Household Products');
Insert into companies(name,sector,industry) values('CME Group','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('CMS Energy','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Coca-Cola Company (The)','Consumer Staples','Soft Drinks & Non-alcoholic Beverages');
Insert into companies(name,sector,industry) values('Cognizant','Information Technology','IT Consulting & Other Services');
Insert into companies(name,sector,industry) values('Colgate-Palmolive','Consumer Staples','Household Products');
Insert into companies(name,sector,industry) values('Comcast','Communication Services','Cable & Satellite');
Insert into companies(name,sector,industry) values('Comerica','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('Conagra Brands','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('ConocoPhillips','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Consolidated Edison','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Constellation Brands','Consumer Staples','Distillers & Vintners');
Insert into companies(name,sector,industry) values('Constellation Energy','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('CooperCompanies','Health Care','Health Care Supplies');
Insert into companies(name,sector,industry) values('Copart','Industrials','Diversified Support Services');
Insert into companies(name,sector,industry) values('Corning Inc.','Information Technology','Electronic Components');
Insert into companies(name,sector,industry) values('Corpay','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Corteva','Materials','Fertilizers & Agricultural Chemicals');
Insert into companies(name,sector,industry) values('CoStar Group','Real Estate','Real Estate Services');
Insert into companies(name,sector,industry) values('Costco','Consumer Staples','Consumer Staples Merchandise Retail');
Insert into companies(name,sector,industry) values('Coterra','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Crown Castle','Real Estate','Telecom Tower REITs');
Insert into companies(name,sector,industry) values('CSX','Industrials','Rail Transportation');
Insert into companies(name,sector,industry) values('Cummins','Industrials','Construction Machinery & Heavy Transportation Equipment');
Insert into companies(name,sector,industry) values('CVS Health','Health Care','Health Care Services');
Insert into companies(name,sector,industry) values('Danaher Corporation','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Darden Restaurants','Consumer Discretionary','Restaurants');
Insert into companies(name,sector,industry) values('DaVita Inc.','Health Care','Health Care Services');
Insert into companies(name,sector,industry) values('Dayforce','Industrials','Human Resource & Employment Services');
Insert into companies(name,sector,industry) values('Deckers Brands','Consumer Discretionary','Footwear');
Insert into companies(name,sector,industry) values('John Deere','Industrials','Agricultural & Farm Machinery');
Insert into companies(name,sector,industry) values('Delta Air Lines','Industrials','Passenger Airlines');
Insert into companies(name,sector,industry) values('Devon Energy','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Dexcom','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Diamondback Energy','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Digital Realty','Real Estate','Data Center REITs');
Insert into companies(name,sector,industry) values('Discover Financial','Financials','Consumer Finance');
Insert into companies(name,sector,industry) values('Dollar General','Consumer Staples','Consumer Staples Merchandise Retail');
Insert into companies(name,sector,industry) values('Dollar Tree','Consumer Staples','Consumer Staples Merchandise Retail');
Insert into companies(name,sector,industry) values('Dominion Energy','Utilities','Multi-Utilities');
Insert into companies(name, sector, industry) values('Domino''s', 'Consumer Discretionary', 'Restaurants');
Insert into companies(name,sector,industry) values('Dover Corporation','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Dow Inc.','Materials','Commodity Chemicals');
Insert into companies(name,sector,industry) values('DR Horton','Consumer Discretionary','Homebuilding');
Insert into companies(name,sector,industry) values('DTE Energy','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Duke Energy','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('DuPont','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('Eastman Chemical Company','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('Eaton Corporation','Industrials','Electrical Components & Equipment');
Insert into companies(name,sector,industry) values('eBay','Consumer Discretionary','Broadline Retail');
Insert into companies(name,sector,industry) values('Ecolab','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('Edison International','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Edwards Lifesciences','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Electronic Arts','Communication Services','Interactive Home Entertainment');
Insert into companies(name,sector,industry) values('Elevance Health','Health Care','Managed Health Care');
Insert into companies(name,sector,industry) values('Eli Lilly and Company','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('Emerson Electric','Industrials','Electrical Components & Equipment');
Insert into companies(name,sector,industry) values('Enphase','Information Technology','Semiconductor Materials & Equipment');
Insert into companies(name,sector,industry) values('Entergy','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('EOG Resources','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('EPAM Systems','Information Technology','IT Consulting & Other Services');
Insert into companies(name,sector,industry) values('EQT Corporation','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Equifax','Industrials','Research & Consulting Services');
Insert into companies(name,sector,industry) values('Equinix','Real Estate','Data Center REITs');
Insert into companies(name,sector,industry) values('Equity Residential','Real Estate','Multi-Family Residential REITs');
Insert into companies(name,sector,industry) values('Essex Property Trust','Real Estate','Multi-Family Residential REITs');
Insert into companies(name,sector,industry) values('Est�e Lauder Companies (The)','Consumer Staples','Personal Care Products');
Insert into companies(name,sector,industry) values('Etsy','Consumer Discretionary','Broadline Retail');
Insert into companies(name,sector,industry) values('Everest Re','Financials','Reinsurance');
Insert into companies(name,sector,industry) values('Evergy','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Eversource','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Exelon','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Expedia Group','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('Expeditors International','Industrials','Air Freight & Logistics');
Insert into companies(name,sector,industry) values('Extra Space Storage','Real Estate','Self-Storage REITs');
Insert into companies(name,sector,industry) values('ExxonMobil','Energy','Integrated Oil & Gas');
Insert into companies(name,sector,industry) values('F5, Inc.','Information Technology','Communications Equipment');
Insert into companies(name,sector,industry) values('FactSet','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('Fair Isaac','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Fastenal','Industrials','Trading Companies & Distributors');
Insert into companies(name,sector,industry) values('Federal Realty','Real Estate','Retail REITs');
Insert into companies(name,sector,industry) values('FedEx','Industrials','Air Freight & Logistics');
Insert into companies(name,sector,industry) values('Fidelity National Information Services','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Fifth Third Bank','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('First Solar','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('FirstEnergy','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Fiserv','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('FMC Corporation','Materials','Fertilizers & Agricultural Chemicals');
Insert into companies(name,sector,industry) values('Ford Motor Company','Consumer Discretionary','Automobile Manufacturers');
Insert into companies(name,sector,industry) values('Fortinet','Information Technology','Systems Software');
Insert into companies(name,sector,industry) values('Fortive','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Fox Corporation (Class A)','Communication Services','Broadcasting');
Insert into companies(name,sector,industry) values('Fox Corporation (Class B)','Communication Services','Broadcasting');
Insert into companies(name,sector,industry) values('Franklin Templeton','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Freeport-McMoRan','Materials','Copper');
Insert into companies(name,sector,industry) values('Garmin','Consumer Discretionary','Consumer Electronics');
Insert into companies(name,sector,industry) values('Gartner','Information Technology','IT Consulting & Other Services');
Insert into companies(name,sector,industry) values('GE Aerospace','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('GE HealthCare','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('GE Vernova','Industrials','Heavy Electrical Equipment');
Insert into companies(name,sector,industry) values('Gen Digital','Information Technology','Systems Software');
Insert into companies(name,sector,industry) values('Generac','Industrials','Electrical Components & Equipment');
Insert into companies(name,sector,industry) values('General Dynamics','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('General Mills','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('General Motors','Consumer Discretionary','Automobile Manufacturers');
Insert into companies(name,sector,industry) values('Genuine Parts Company','Consumer Discretionary','Distributors');
Insert into companies(name,sector,industry) values('Gilead Sciences','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Global Payments','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Globe Life','Financials','Life & Health Insurance');
Insert into companies(name,sector,industry) values('Goldman Sachs','Financials','Investment Banking & Brokerage');
Insert into companies(name,sector,industry) values('Halliburton','Energy','Oil & Gas Equipment & Services');
Insert into companies(name,sector,industry) values('Hartford (The)','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Hasbro','Consumer Discretionary','Leisure Products');
Insert into companies(name,sector,industry) values('HCA Healthcare','Health Care','Health Care Facilities');
Insert into companies(name,sector,industry) values('Healthpeak','Real Estate','Health Care REITs');
Insert into companies(name,sector,industry) values('Henry Schein','Health Care','Health Care Distributors');
Insert into companies(name,sector,industry) values('Hershey''s','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Hess Corporation','Energy','Integrated Oil & Gas');
Insert into companies(name,sector,industry) values('Hewlett Packard Enterprise','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('Hilton Worldwide','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('Hologic','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Home Depot (The)','Consumer Discretionary','Home Improvement Retail');
Insert into companies(name,sector,industry) values('Honeywell','Industrials','Industrial Conglomerates');
Insert into companies(name,sector,industry) values('Hormel Foods','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Host Hotels & Resorts','Real Estate','Hotel & Resort REITs');
Insert into companies(name,sector,industry) values('Howmet Aerospace','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('HP Inc.','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('Hubbell Incorporated','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Humana','Health Care','Managed Health Care');
Insert into companies(name,sector,industry) values('Huntington Bancshares','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Huntington Ingalls Industries','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('IBM','Information Technology','IT Consulting & Other Services');
Insert into companies(name,sector,industry) values('IDEX Corporation','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Idexx Laboratories','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Illinois Tool Works','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Illumina','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Incyte','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Ingersoll Rand','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Insulet Corporation','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Intel','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Intercontinental Exchange','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('International Flavors & Fragrances','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('International Paper','Materials','Paper & Plastic Packaging Products & Materials');
Insert into companies(name,sector,industry) values('Interpublic Group of Companies (The)','Communication Services','Advertising');
Insert into companies(name,sector,industry) values('Intuit','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Intuitive Surgical','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Invesco','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Invitation Homes','Real Estate','Single-Family Residential REITs');
Insert into companies(name,sector,industry) values('IQVIA','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('Iron Mountain','Real Estate','Other Specialized REITs');
Insert into companies(name,sector,industry) values('J.B. Hunt','Industrials','Cargo Ground Transportation');
Insert into companies(name,sector,industry) values('Jabil','Information Technology','Electronic Manufacturing Services');
Insert into companies(name,sector,industry) values('Jack Henry & Associates','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Jacobs Solutions','Industrials','Construction & Engineering');
Insert into companies(name,sector,industry) values('Johnson & Johnson','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('Johnson Controls','Industrials','Building Products');
Insert into companies(name,sector,industry) values('JPMorgan Chase','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('Juniper Networks','Information Technology','Communications Equipment');
Insert into companies(name,sector,industry) values('Kellanova','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Kenvue','Consumer Staples','Personal Care Products');
Insert into companies(name,sector,industry) values('Keurig Dr Pepper','Consumer Staples','Soft Drinks & Non-alcoholic Beverages');
Insert into companies(name,sector,industry) values('KeyCorp','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Keysight','Information Technology','Electronic Equipment & Instruments');
Insert into companies(name,sector,industry) values('Kimberly-Clark','Consumer Staples','Household Products');
Insert into companies(name,sector,industry) values('Kimco Realty','Real Estate','Retail REITs');
Insert into companies(name,sector,industry) values('Kinder Morgan','Energy','Oil & Gas Storage & Transportation');
Insert into companies(name,sector,industry) values('KLA Corporation','Information Technology','Semiconductor Materials & Equipment');
Insert into companies(name,sector,industry) values('Kraft Heinz','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Kroger','Consumer Staples','Food Retail');
Insert into companies(name,sector,industry) values('L3Harris','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('LabCorp','Health Care','Health Care Services');
Insert into companies(name,sector,industry) values('Lam Research','Information Technology','Semiconductor Materials & Equipment');
Insert into companies(name,sector,industry) values('Lamb Weston','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Las Vegas Sands','Consumer Discretionary','Casinos & Gaming');
Insert into companies(name,sector,industry) values('Leidos','Industrials','Diversified Support Services');
Insert into companies(name,sector,industry) values('Lennar','Consumer Discretionary','Homebuilding');
Insert into companies(name,sector,industry) values('Linde plc','Materials','Industrial Gases');
Insert into companies(name,sector,industry) values('Live Nation Entertainment','Communication Services','Movies & Entertainment');
Insert into companies(name,sector,industry) values('LKQ Corporation','Consumer Discretionary','Distributors');
Insert into companies(name,sector,industry) values('Lockheed Martin','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Loews Corporation','Financials','Multi-line Insurance');
Insert into companies(name,sector,industry) values('Lowe''s','Consumer Discretionary','Home Improvement Retail');
Insert into companies(name,sector,industry) values('Lululemon Athletica','Consumer Discretionary','Apparel, Accessories & Luxury Goods');
Insert into companies(name,sector,industry) values('LyondellBasell','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('M&T Bank','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Marathon Oil','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Marathon Petroleum','Energy','Oil & Gas Refining & Marketing');
Insert into companies(name,sector,industry) values('MarketAxess','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('Marriott International','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('Marsh McLennan','Financials','Insurance Brokers');
Insert into companies(name,sector,industry) values('Martin Marietta Materials','Materials','Construction Materials');
Insert into companies(name,sector,industry) values('Masco','Industrials','Building Products');
Insert into companies(name,sector,industry) values('Mastercard','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Match Group','Communication Services','Interactive Media & Services');
Insert into companies(name,sector,industry) values('McCormick & Company','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('McDonald''s','Consumer Discretionary','Restaurants');
Insert into companies(name,sector,industry) values('McKesson Corporation','Health Care','Health Care Distributors');
Insert into companies(name,sector,industry) values('Medtronic','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Merck & Co.','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('Meta Platforms','Communication Services','Interactive Media & Services');
Insert into companies(name,sector,industry) values('MetLife','Financials','Life & Health Insurance');
Insert into companies(name,sector,industry) values('Mettler Toledo','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('MGM Resorts','Consumer Discretionary','Casinos & Gaming');
Insert into companies(name,sector,industry) values('Microchip Technology','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Micron Technology','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Microsoft','Information Technology','Systems Software');
Insert into companies(name,sector,industry) values('Mid-America Apartment Communities','Real Estate','Multi-Family Residential REITs');
Insert into companies(name,sector,industry) values('Moderna','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Mohawk Industries','Consumer Discretionary','Home Furnishings');
Insert into companies(name,sector,industry) values('Molina Healthcare','Health Care','Managed Health Care');
Insert into companies(name,sector,industry) values('Molson Coors Beverage Company','Consumer Staples','Brewers');
Insert into companies(name,sector,industry) values('Mondelez International','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Monolithic Power Systems','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Monster Beverage','Consumer Staples','Soft Drinks & Non-alcoholic Beverages');
Insert into companies(name,sector,industry) values('Moody''s Corporation','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('Morgan Stanley','Financials','Investment Banking & Brokerage');
Insert into companies(name,sector,industry) values('Mosaic Company (The)','Materials','Fertilizers & Agricultural Chemicals');
Insert into companies(name,sector,industry) values('Motorola Solutions','Information Technology','Communications Equipment');
Insert into companies(name,sector,industry) values('MSCI','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('Nasdaq, Inc.','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('NetApp','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('Netflix','Communication Services','Movies & Entertainment');
Insert into companies(name,sector,industry) values('Newmont','Materials','Gold');
Insert into companies(name,sector,industry) values('News Corp (Class A)','Communication Services','Publishing');
Insert into companies(name,sector,industry) values('News Corp (Class B)','Communication Services','Publishing');
Insert into companies(name,sector,industry) values('NextEra Energy','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Nike, Inc.','Consumer Discretionary','Apparel, Accessories & Luxury Goods');
Insert into companies(name,sector,industry) values('NiSource','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Nordson Corporation','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Norfolk Southern Railway','Industrials','Rail Transportation');
Insert into companies(name,sector,industry) values('Northern Trust','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Northrop Grumman','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Norwegian Cruise Line Holdings','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('NRG Energy','Utilities','Independent Power Producers & Energy Traders');
Insert into companies(name,sector,industry) values('Nucor','Materials','Steel');
Insert into companies(name,sector,industry) values('Nvidia','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('NVR, Inc.','Consumer Discretionary','Homebuilding');
Insert into companies(name,sector,industry) values('NXP Semiconductors','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('O''Reilly Auto Parts','Consumer Discretionary','Automotive Retail');
Insert into companies(name,sector,industry) values('Occidental Petroleum','Energy','Oil & Gas Exploration & Production');
Insert into companies(name,sector,industry) values('Old Dominion','Industrials','Cargo Ground Transportation');
Insert into companies(name,sector,industry) values('Omnicom Group','Communication Services','Advertising');
Insert into companies(name,sector,industry) values('ON Semiconductor','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('ONEOK','Energy','Oil & Gas Storage & Transportation');
Insert into companies(name,sector,industry) values('Oracle Corporation','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Otis Worldwide','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Paccar','Industrials','Construction Machinery & Heavy Transportation Equipment');
Insert into companies(name,sector,industry) values('Packaging Corporation of America','Materials','Paper & Plastic Packaging Products & Materials');
Insert into companies(name,sector,industry) values('Palo Alto Networks','Information Technology','Systems Software');
Insert into companies(name,sector,industry) values('Paramount Global','Communication Services','Movies & Entertainment');
Insert into companies(name,sector,industry) values('Parker Hannifin','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Paychex','Industrials','Human Resource & Employment Services');
Insert into companies(name,sector,industry) values('Paycom','Industrials','Human Resource & Employment Services');
Insert into companies(name,sector,industry) values('PayPal','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Pentair','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('PepsiCo','Consumer Staples','Soft Drinks & Non-alcoholic Beverages');
Insert into companies(name,sector,industry) values('Pfizer','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('PG&E Corporation','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Philip Morris International','Consumer Staples','Tobacco');
Insert into companies(name,sector,industry) values('Phillips 66','Energy','Oil & Gas Refining & Marketing');
Insert into companies(name,sector,industry) values('Pinnacle West','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('PNC Financial Services','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Pool Corporation','Consumer Discretionary','Distributors');
Insert into companies(name,sector,industry) values('PPG Industries','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('PPL Corporation','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Principal Financial Group','Financials','Life & Health Insurance');
Insert into companies(name,sector,industry) values('Procter & Gamble','Consumer Staples','Personal Care Products');
Insert into companies(name,sector,industry) values('Progressive Corporation','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Prologis','Real Estate','Industrial REITs');
Insert into companies(name,sector,industry) values('Prudential Financial','Financials','Life & Health Insurance');
Insert into companies(name,sector,industry) values('Public Service Enterprise Group','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('PTC','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Public Storage','Real Estate','Self-Storage REITs');
Insert into companies(name,sector,industry) values('PulteGroup','Consumer Discretionary','Homebuilding');
Insert into companies(name,sector,industry) values('Qorvo','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Quanta Services','Industrials','Construction & Engineering');
Insert into companies(name,sector,industry) values('Qualcomm','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Quest Diagnostics','Health Care','Health Care Services');
Insert into companies(name,sector,industry) values('Ralph Lauren Corporation','Consumer Discretionary','Apparel, Accessories & Luxury Goods');
Insert into companies(name,sector,industry) values('Raymond James','Financials','Investment Banking & Brokerage');
Insert into companies(name,sector,industry) values('RTX Corporation','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Realty Income','Real Estate','Retail REITs');
Insert into companies(name,sector,industry) values('Regency Centers','Real Estate','Retail REITs');
Insert into companies(name,sector,industry) values('Regeneron','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Regions Financial Corporation','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Republic Services','Industrials','Environmental & Facilities Services');
Insert into companies(name,sector,industry) values('ResMed','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Revvity','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Robert Half','Industrials','Human Resource & Employment Services');
Insert into companies(name,sector,industry) values('Rockwell Automation','Industrials','Electrical Components & Equipment');
Insert into companies(name,sector,industry) values('Rollins, Inc.','Industrials','Environmental & Facilities Services');
Insert into companies(name,sector,industry) values('Roper Technologies','Information Technology','Electronic Equipment & Instruments');
Insert into companies(name,sector,industry) values('Ross Stores','Consumer Discretionary','Apparel Retail');
Insert into companies(name,sector,industry) values('Royal Caribbean Group','Consumer Discretionary','Hotels, Resorts & Cruise Lines');
Insert into companies(name,sector,industry) values('S&P Global','Financials','Financial Exchanges & Data');
Insert into companies(name,sector,industry) values('Salesforce','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('SBA Communications','Real Estate','Telecom Tower REITs');
Insert into companies(name,sector,industry) values('Schlumberger','Energy','Oil & Gas Equipment & Services');
Insert into companies(name,sector,industry) values('Seagate Technology','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('Sempra Energy','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('ServiceNow','Information Technology','Systems Software');
Insert into companies(name,sector,industry) values('Sherwin-Williams','Materials','Specialty Chemicals');
Insert into companies(name,sector,industry) values('Simon Property Group','Real Estate','Retail REITs');
Insert into companies(name,sector,industry) values('Skyworks Solutions','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('J.M. Smucker Company (The)','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('Snap-on','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Solventum','Health Care','Health Care Technology');
Insert into companies(name,sector,industry) values('Southern Company','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Southwest Airlines','Industrials','Passenger Airlines');
Insert into companies(name,sector,industry) values('Stanley Black & Decker','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Starbucks','Consumer Discretionary','Restaurants');
Insert into companies(name,sector,industry) values('State Street Corporation','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Steel Dynamics','Materials','Steel');
Insert into companies(name,sector,industry) values('Steris','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Stryker Corporation','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Supermicro','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('Synchrony Financial','Financials','Consumer Finance');
Insert into companies(name,sector,industry) values('Synopsys','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Sysco','Consumer Staples','Food Distributors');
Insert into companies(name,sector,industry) values('T-Mobile US','Communication Services','Wireless Telecommunication Services');
Insert into companies(name,sector,industry) values('T. Rowe Price','Financials','Asset Management & Custody Banks');
Insert into companies(name,sector,industry) values('Take-Two Interactive','Communication Services','Interactive Home Entertainment');
Insert into companies(name,sector,industry) values('Tapestry, Inc.','Consumer Discretionary','Apparel, Accessories & Luxury Goods');
Insert into companies(name,sector,industry) values('Targa Resources','Energy','Oil & Gas Storage & Transportation');
Insert into companies(name,sector,industry) values('Target Corporation','Consumer Staples','Consumer Staples Merchandise Retail');
Insert into companies(name,sector,industry) values('TE Connectivity','Information Technology','Electronic Manufacturing Services');
Insert into companies(name,sector,industry) values('Teledyne Technologies','Information Technology','Electronic Equipment & Instruments');
Insert into companies(name,sector,industry) values('Teleflex','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Teradyne','Information Technology','Semiconductor Materials & Equipment');
Insert into companies(name,sector,industry) values('Tesla, Inc.','Consumer Discretionary','Automobile Manufacturers');
Insert into companies(name,sector,industry) values('Texas Instruments','Information Technology','Semiconductors');
Insert into companies(name,sector,industry) values('Textron','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Thermo Fisher Scientific','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('TJX Companies','Consumer Discretionary','Apparel Retail');
Insert into companies(name,sector,industry) values('Tractor Supply','Consumer Discretionary','Other Specialty Retail');
Insert into companies(name,sector,industry) values('Trane Technologies','Industrials','Building Products');
Insert into companies(name,sector,industry) values('TransDigm Group','Industrials','Aerospace & Defense');
Insert into companies(name,sector,industry) values('Travelers Companies (The)','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('Trimble Inc.','Information Technology','Electronic Equipment & Instruments');
Insert into companies(name,sector,industry) values('Truist','Financials','Regional Banks');
Insert into companies(name,sector,industry) values('Tyler Technologies','Information Technology','Application Software');
Insert into companies(name,sector,industry) values('Tyson Foods','Consumer Staples','Packaged Foods & Meats');
Insert into companies(name,sector,industry) values('U.S. Bank','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('Uber','Industrials','Passenger Ground Transportation');
Insert into companies(name,sector,industry) values('UDR, Inc.','Real Estate','Multi-Family Residential REITs');
Insert into companies(name,sector,industry) values('Ulta Beauty','Consumer Discretionary','Other Specialty Retail');
Insert into companies(name,sector,industry) values('Union Pacific Corporation','Industrials','Rail Transportation');
Insert into companies(name,sector,industry) values('United Airlines Holdings','Industrials','Passenger Airlines');
Insert into companies(name,sector,industry) values('United Parcel Service','Industrials','Air Freight & Logistics');
Insert into companies(name,sector,industry) values('United Rentals','Industrials','Trading Companies & Distributors');
Insert into companies(name,sector,industry) values('UnitedHealth Group','Health Care','Managed Health Care');
Insert into companies(name,sector,industry) values('Universal Health Services','Health Care','Health Care Facilities');
Insert into companies(name,sector,industry) values('Valero Energy','Energy','Oil & Gas Refining & Marketing');
Insert into companies(name,sector,industry) values('Ventas','Real Estate','Health Care REITs');
Insert into companies(name,sector,industry) values('Veralto','Industrials','Environmental & Facilities Services');
Insert into companies(name,sector,industry) values('Verisign','Information Technology','Internet Services & Infrastructure');
Insert into companies(name,sector,industry) values('Verisk','Industrials','Research & Consulting Services');
Insert into companies(name,sector,industry) values('Verizon','Communication Services','Integrated Telecommunication Services');
Insert into companies(name,sector,industry) values('Vertex Pharmaceuticals','Health Care','Biotechnology');
Insert into companies(name,sector,industry) values('Viatris','Health Care','Pharmaceuticals');
Insert into companies(name,sector,industry) values('Vici Properties','Real Estate','Hotel & Resort REITs');
Insert into companies(name,sector,industry) values('Visa Inc.','Financials','Transaction & Payment Processing Services');
Insert into companies(name,sector,industry) values('Vistra','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Vulcan Materials Company','Materials','Construction Materials');
Insert into companies(name,sector,industry) values('W. R. Berkley Corporation','Financials','Property & Casualty Insurance');
Insert into companies(name,sector,industry) values('W. W. Grainger','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Wabtec','Industrials','Construction Machinery & Heavy Transportation Equipment');
Insert into companies(name,sector,industry) values('Walgreens Boots Alliance','Consumer Staples','Drug Retail');
Insert into companies(name,sector,industry) values('Walmart','Consumer Staples','Consumer Staples Merchandise Retail');
Insert into companies(name,sector,industry) values('Walt Disney Company (The)','Communication Services','Movies & Entertainment');
Insert into companies(name,sector,industry) values('Warner Bros. Discovery','Communication Services','Broadcasting');
Insert into companies(name,sector,industry) values('Waste Management','Industrials','Environmental & Facilities Services');
Insert into companies(name,sector,industry) values('Waters Corporation','Health Care','Life Sciences Tools & Services');
Insert into companies(name,sector,industry) values('WEC Energy Group','Utilities','Electric Utilities');
Insert into companies(name,sector,industry) values('Wells Fargo','Financials','Diversified Banks');
Insert into companies(name,sector,industry) values('Welltower','Real Estate','Health Care REITs');
Insert into companies(name,sector,industry) values('West Pharmaceutical Services','Health Care','Health Care Supplies');
Insert into companies(name,sector,industry) values('Western Digital','Information Technology','Technology Hardware, Storage & Peripherals');
Insert into companies(name,sector,industry) values('WestRock','Materials','Paper & Plastic Packaging Products & Materials');
Insert into companies(name,sector,industry) values('Weyerhaeuser','Real Estate','Timber REITs');
Insert into companies(name,sector,industry) values('Williams Companies','Energy','Oil & Gas Storage & Transportation');
Insert into companies(name,sector,industry) values('Willis Towers Watson','Financials','Insurance Brokers');
Insert into companies(name,sector,industry) values('Wynn Resorts','Consumer Discretionary','Casinos & Gaming');
Insert into companies(name,sector,industry) values('Xcel Energy','Utilities','Multi-Utilities');
Insert into companies(name,sector,industry) values('Xylem Inc.','Industrials','Industrial Machinery & Supplies & Components');
Insert into companies(name,sector,industry) values('Yum! Brands','Consumer Discretionary','Restaurants');
Insert into companies(name,sector,industry) values('Zebra Technologies','Information Technology','Electronic Equipment & Instruments');
Insert into companies(name,sector,industry) values('Zimmer Biomet','Health Care','Health Care Equipment');
Insert into companies(name,sector,industry) values('Zoetis','Health Care','Pharmaceuticals');
